export const ADD_ITEMS = 'add-items';
export const CREATE_FOLDER = 'create-folder';
export const ADD_IMAGES_AND_VIDEOS = 'add-images-and-videos';
export const ADD_DOCUMENTS = 'add-documents';
export const FOLDER_NAME_INPUT = 'folder-name-input';
export const CONFIRM_CREATE_FOLDER = 'confirm-create-folder';
export const CANCEL_CREATE_FOLDER = 'cancel-create-folder';
export const HOME_TAB = 'home-tab';
export const MY_ITEMS_TAB = 'my-items-tab';
export const SHARED_ITEMS_TAB = 'shared-items-tab';
export const PROFILE_TAB = 'profile-tab';
export const LIBRARY_TAB = 'library-tab';
export const SIGN_IN_TAB = 'sign-in-tab';
export const ITEM_LIST = 'item-list';
export const ITEM_LIST_OPTIONS = 'item-list-options';
export const ITEM_LIST_OPTIONS_DETAILS = 'item-list-options-details';
export const ITEM_LIST_OPTIONS_EDIT = 'item-list-options-edit';
export const ITEM_LIST_OPTIONS_DELETE = 'item-list-options-delete';
export const ITEM_LIST_OPTIONS_SHARE = 'item-list-options-share';
export const CONFIRM_EDIT_ITEM = 'confirm-edit-item';
export const CANCEL_EDIT_ITEM = 'cancel-edit-item';
export const EDIT_ITEM_NAME_INPUT = 'edit-item-name-input';
export const CONFIRM_DELETE_ITEM = 'confirm-delete-item';
export const CANCEL_DELETE_ITEM = 'cancel-delete-item';
export const SHARE_ITEM_PLAYER = 'share-item-player';
export const SHARE_ITEM_BUILDER = 'share-item-builder';
export const PDF_ITEM = 'pdf_item';
export const PDF_SHARE = 'pdf_share';
export const VIDEO_ITEM = 'video_item';
export const VIDEO_SAVE = 'video-save';
export const VIDEO_SHARE = 'video-share';
export const IMAGE_ITEM = 'image_item';
export const IMAGE_SAVE = 'image-save';
export const IMAGE_SHARE = 'image-share';
export const UNSUPPORTED_SHARE = 'unsupported-share';
export const SIGN_IN_BUTTON = 'sign-in';
export const SIGN_UP_BUTTON = 'sign-up';
export const DETOX_SIGN_IN_BUTTON = 'detox-sign-in-button';
export const LOG_OUT_BUTTON = 'log-out-button';
export const URL_INPUT = 'url-input';
export const SIGN_IN_LATER_BUTTON = 'sign-in-later-button';
export const FOLDER_SCREEN_BACK_BUTTON = 'folder-screen-back-button';
export const DETAILS_SCREEN_BACK_BUTTON = 'details-screen-back-button';
export const ITEM_NAVIGATOR_ITEM_BACK_BUTTON = 'item-screen-back-button';
export const SCAN_QR_CODE_BUTTON = 'scan-qr-code-button';
export const buildItemsListTestId = (id: string) => `items-list-${id}`;
export const URL_INPUT_SUBMIT_BUTTON = 'url-input-submit-button';
export const buildPlayerButtonId = (id: string) => `player-button-${id}`;
export const ITEM_NAVIGATOR_ITEM_ERROR = 'item-screen-error';
export const LIBRARY_SEARCH_BAR = 'library-search-bar';
export const PLAYER_FOLDER_MENU = 'player-folder-menu';
export const buildPlayerFolderMenuItem = (id: string) =>
  `player-folder-menu-item-${id}`;
export const buildPlayerViewCloseButton = (id: string) =>
  `player-view-close-button-${id}`;
export const CHAT_WRAPPER = 'chat-wrapper';
export const CHAT_BUTTON_HEADER = 'chat-button-header';
export const CHAT_MESSAGE_OPTIONS_EDIT = 'chat-message-options-edit';
export const CHAT_MESSAGE_OPTIONS_CANCEL_EDIT = 'chat-message-options-cancel-edit';
export const CHAT_MESSAGE_OPTIONS_DELETE = 'chat-message-options-delete';
export const CHAT_INPUT_TEXT = 'chat-input-text';
export const CHAT_SEND_BUTTON = 'chat-send-button';
export const buildChatMessageId = (id: string) => `chat-message-${id}`;
export const buildChatMentionMemberId = (name: string) => `chat-member-${name}`;
export const buildTestFolderChatId = (date: string) => `chat-${date}`;

export const SLEEP_TIME_HEAVY_ITEMS = 10000;
export const SLEEP_TIME_LIGHT_ITEMS = 5000;
export const SLEEP_TIME_OPEN_APP = 3000;
export const SLEEP_TIME_MINIMUM = 1000;
export const buildLibraryCardId = (id: string) => `library-card-${id}`;
export const COLLECTION_BOOKMARK_BUTTON = 'collection-bookmark-button';
